dist: bionic
language: python
env:
  global:
    secure: "aA9FSzRVovg0uJ9iVUNen8yf4Y8kktabiaIsv6FpqFi7zKtvB2BdrckKF1A7FT4oSQDyQOairjezmSKHBLOiE4RfCuoGLk/ob02E/YewbMCJxtoi9xBOymnalcZ0BWVmyRsGY/1DP42hAECjSL9Z18Jj8uU0VleJXF4MW8PNf7I7mVFUK4iudyJabaoD9udVZuSDcDZLtfrhs5BcbhlHjnu86mvpQp2qvUjpoLB1ybbC/KxuAfMlRH3ZxgKdFpqx6C8ZRqeeQf+gw/eqnauhUjusJAmlGeedFZt5iJclqg8+cO3mVyV7XHohlZC8yFO0orhk+MioS+/Hha/APWCL9a8q6HIoHev0NKvpbK//W/qW9iPwMGbXuoZBb0YM1hcsUgbwXP0w1uuv90s86WpD7pR6++hiD+araPvvoCDO+mRZPAjU6GbXTwJO46c4ENxGewEkLdhyIMEbAQHam/PoRES1UyzI3Jy6Xwx2hxBAk+LPNkiWcRXVgtxYAWbYCIf1164xLHuISKEyWpKWG8CsrCK/J4gp8J7Ua0YXktLoRF/w9EPzcpzUlr0Ipktq0P8OGlLmT6hULTNeL+RR3rSlnIBEI6x/iXzvR/IlNOd63WQRPklSaKWygRK5dWyapOAHX0FHUfQyaVtOhhP1CbVj9bgW7vt6tGebTmAzQMxnmas="
jobs:
  include:
    - python: 3.6
      env: DB=sqlite3
    - python: 3.7
      env: DB=mysql
    - python: 3.8
      env: DB=postgresql
services: [mysql, postgresql]
before_install:
  - |
    if [ "$DB" = 'mysql' ]; then
      mysql -u root -e 'CREATE DATABASE IF NOT EXISTS mangadv;'
    fi
  - |
    if [ "$DB" = 'postgresql' ]; then
      psql -U postgres -c 'DROP DATABASE IF EXISTS mangadv;'
      psql -U postgres -c 'CREATE DATABASE mangadv;'
    fi
install: pip install -e .[dev,mysql,pgsql]
before_script:
  - pip install coveralls
script:
  - python setup.py flake8
  - python setup.py isort
  - py.test --cov-report=xml
  - coveralls
