site_name: MangAdventure
repo_url: https://github.com/evangelos-ch/MangAdventure
docs_dir: docs
pages:
  - Home: index.md
  - Compatibility: compatibility.md
  - Changelog: changelog.md
  - Roadmap: roadmap.md
markdown_extensions: [meta, tables, fenced_code]

